In [6]:
import xlrd
import MySQLdb

In [7]:
# 1. Establish a MySQL connection
database = MySQLdb.connect (host="localhost", user = "root", passwd = "1234", db = "dm_course_v3")

# # 2. Open the workbook and define the worksheet
# book = xlrd.open_workbook("Sample - Superstore - cleaned.xls")

### Segment

In [4]:
# 1. Open the workbook and define the worksheet
sheet = book.sheet_by_name("segment")

# 2. Get the cursor, which is used to traverse the database, line by line
cursor = database.cursor()

In [5]:
# 3, Create the INSERT INTO sql query
query = """INSERT INTO segment (Segment, segment_id) VALUES (%s, %s)"""

# 4. Create a For loop to iterate through each row in the XLS file, starting at row 2 to skip the headers
for r in range(1, sheet.nrows):
    if sheet.cell(r,0).value != '':
        col_name_0 = sheet.cell(r,0).value
        col_name_1  = int(sheet.cell(r,1).value)


        # Assign values from each row
        values = (col_name_0, col_name_1)
        print(values)
        # Execute sql Query
        cursor.execute(query, values)
    else:
        pass

# Close the cursor
cursor.close()
# Commit the transaction
database.commit()
# Close the database connection
database.close()

# 5. Status
print('ETL - copleted')

('Consumer', 1)
('Corporate', 2)
('Home Office', 3)
ETL - copleted

### Product

In [6]:
# 1. Open the workbook and define the worksheet
sheet = book.sheet_by_name("product")

# 2. Get the cursor, which is used to traverse the database, line by line
cursor = database.cursor()

In [8]:
# 3, Create the INSERT INTO sql query
query = """INSERT INTO product ('Product ID', 'Product Name', sub_category_id) VALUES (%s, %s, %s)"""

# 4. Create a For loop to iterate through each row in the XLS file, starting at row 2 to skip the headers
for r in range(1, sheet.nrows):
    col_name_0 = sheet.cell(r,0).value
    col_name_1  = sheet.cell(r,1).value
    col_name_2  = int(sheet.cell(r,2).value)

    
    # Assign values from each row
    values = (col_name_0, col_name_1, col_name_2)
    print(values)

    # Execute sql Query
    cursor.execute(query, values)

# Close the cursor
cursor.close()
# Commit the transaction
database.commit()
# Close the database connection
database.close()

# 5. Status
print('ETL - copleted')

### City

In [3]:
# 1. Open the workbook and define the worksheet
sheet = book.sheet_by_name("city")

# 2. Get the cursor, which is used to traverse the database, line by line
cursor = database.cursor()

In [4]:
# 3, Create the INSERT INTO sql query
query = """INSERT INTO city (City, Country_Region, State, Region, city_id) VALUES (%s, %s, %s, %s, %s)"""

# 4. Create a For loop to iterate through each row in the XLS file, starting at row 2 to skip the headers
for r in range(1, sheet.nrows):
    if sheet.cell(r,0).value != '':
        col_name_0 = sheet.cell(r,0).value
        col_name_1  = sheet.cell(r,1).value
        col_name_2  = sheet.cell(r,2).value
        col_name_3  = sheet.cell(r,3).value
        col_name_4  = int(sheet.cell(r,4).value)
        
        # Assign values from each row
        values = (col_name_0, col_name_1, col_name_2, col_name_3, col_name_4)
        print(values)

        # Execute sql Query
        cursor.execute(query, values)
    else:
        pass

# Close the cursor
cursor.close()
# Commit the transaction
database.commit()
# Close the database connection
database.close()

# 5. Status
print('ETL - copleted')

('Aberdeen', 'United States', 'South Dakota', 'Central', 1)
('Abilene', 'United States', 'Texas', 'Central', 2)
('Akron', 'United States', 'Ohio', 'East', 3)
('Albuquerque', 'United States', 'New Mexico', 'West', 4)
('Alexandria', 'United States', 'Virginia', 'South', 5)
('Allen', 'United States', 'Texas', 'Central', 6)
('Allentown', 'United States', 'Pennsylvania', 'East', 7)
('Altoona', 'United States', 'Pennsylvania', 'East', 8)
('Amarillo', 'United States', 'Texas', 'Central', 9)
('Anaheim', 'United States', 'California', 'West', 10)
('Andover', 'United States', 'Massachusetts', 'East', 11)
('Ann Arbor', 'United States', 'Michigan', 'Central', 12)
('Antioch', 'United States', 'California', 'West', 13)
('Apopka', 'United States', 'Florida', 'South', 14)
('Apple Valley', 'United States', 'California', 'West', 15)
('Apple Valley', 'United States', 'Minnesota', 'Central', 16)
('Appleton', 'United States', 'Wisconsin', 'Central', 17)
('Arlington', 'United States', 'Texas', 'Central', 18)
('Arlington', 'United States', 'Virginia', 'South', 19)
('Arlington Heights', 'United States', 'Illinois', 'Central', 20)
('Arvada', 'United States', 'Colorado', 'West', 21)
('Asheville', 'United States', 'North Carolina', 'South', 22)
('Athens', 'United States', 'Georgia', 'South', 23)
('Atlanta', 'United States', 'Georgia', 'South', 24)
('Atlantic City', 'United States', 'New Jersey', 'East', 25)
('Auburn', 'United States', 'Alabama', 'South', 26)
('Auburn', 'United States', 'New York', 'East', 27)
('Aurora', 'United States', 'Colorado', 'West', 28)
('Aurora', 'United States', 'Illinois', 'Central', 29)
('Austin', 'United States', 'Texas', 'Central', 30)
('Avondale', 'United States', 'Arizona', 'West', 31)
('Bakersfield', 'United States', 'California', 'West', 32)
('Baltimore', 'United States', 'Maryland', 'East', 33)
('Bangor', 'United States', 'Maine', 'East', 34)
('Bartlett', 'United States', 'Tennessee', 'South', 35)
('Bayonne', 'United States', 'New Jersey', 'East', 36)
('Baytown', 'United States', 'Texas', 'Central', 37)
('Beaumont', 'United States', 'Texas', 'Central', 38)
('Bedford', 'United States', 'Texas', 'Central', 39)
('Belleville', 'United States', 'New Jersey', 'East', 40)
('Bellevue', 'United States', 'Washington', 'West', 41)
('Bellingham', 'United States', 'Washington', 'West', 42)
('Bethlehem', 'United States', 'Pennsylvania', 'East', 43)
('Beverly', 'United States', 'Massachusetts', 'East', 44)
('Billings', 'United States', 'Montana', 'West', 45)
('Bloomington', 'United States', 'Illinois', 'Central', 46)
('Bloomington', 'United States', 'Indiana', 'Central', 47)
('Boca Raton', 'United States', 'Florida', 'South', 48)
('Boise', 'United States', 'Idaho', 'West', 49)
('Bolingbrook', 'United States', 'Illinois', 'Central', 50)
('Bossier City', 'United States', 'Louisiana', 'South', 51)
('Bowling Green', 'United States', 'Kentucky', 'South', 52)
('Bowling Green', 'United States', 'Ohio', 'East', 53)
('Boynton Beach', 'United States', 'Florida', 'South', 54)
('Bozeman', 'United States', 'Montana', 'West', 55)
('Brentwood', 'United States', 'California', 'West', 56)
('Bridgeton', 'United States', 'New Jersey', 'East', 57)
('Bristol', 'United States', 'Connecticut', 'East', 58)
('Bristol', 'United States', 'Tennessee', 'South', 59)
('Broken Arrow', 'United States', 'Oklahoma', 'Central', 60)
('Broomfield', 'United States', 'Colorado', 'West', 61)
('Brownsville', 'United States', 'Texas', 'Central', 62)
('Bryan', 'United States', 'Texas', 'Central', 63)
('Buffalo', 'United States', 'New York', 'East', 64)
('Buffalo Grove', 'United States', 'Illinois', 'Central', 65)
('Bullhead City', 'United States', 'Arizona', 'West', 66)
('Burbank', 'United States', 'California', 'West', 67)
('Burlington', 'United States', 'Iowa', 'Central', 68)
('Burlington', 'United States', 'North Carolina', 'South', 69)
('Caldwell', 'United States', 'Idaho', 'West', 70)
('Camarillo', 'United States', 'California', 'West', 71)
('Cambridge', 'United States', 'Massachusetts', 'East', 72)
('Canton', 'United States', 'Michigan', 'Central', 73)
('Carlsbad', 'United States', 'New Mexico', 'West', 74)
('Carol Stream', 'United States', 'Illinois', 'Central', 75)
('Carrollton', 'United States', 'Texas', 'Central', 76)
('Cary', 'United States', 'North Carolina', 'South', 77)
('Cedar Hill', 'United States', 'Texas', 'Central', 78)
('Cedar Rapids', 'United States', 'Iowa', 'Central', 79)
('Champaign', 'United States', 'Illinois', 'Central', 80)
('Chandler', 'United States', 'Arizona', 'West', 81)
('Chapel Hill', 'United States', 'North Carolina', 'South', 82)
('Charlotte', 'United States', 'North Carolina', 'South', 83)
('Charlottesville', 'United States', 'Virginia', 'South', 84)
('Chattanooga', 'United States', 'Tennessee', 'South', 85)
('Chesapeake', 'United States', 'Virginia', 'South', 86)
('Chester', 'United States', 'Pennsylvania', 'East', 87)
('Cheyenne', 'United States', 'Wyoming', 'West', 88)
('Chicago', 'United States', 'Illinois', 'Central', 89)
('Chico', 'United States', 'California', 'West', 90)
('Chula Vista', 'United States', 'California', 'West', 91)
('Cincinnati', 'United States', 'Ohio', 'East', 92)
('Citrus Heights', 'United States', 'California', 'West', 93)
('Clarksville', 'United States', 'Tennessee', 'South', 94)
('Cleveland', 'United States', 'Ohio', 'East', 95)
('Clifton', 'United States', 'New Jersey', 'East', 96)
('Clinton', 'United States', 'Maryland', 'East', 97)
('Clovis', 'United States', 'New Mexico', 'West', 98)
('Coachella', 'United States', 'California', 'West', 99)
('College Station', 'United States', 'Texas', 'Central', 100)
('Colorado Springs', 'United States', 'Colorado', 'West', 101)
('Columbia', 'United States', 'Maryland', 'East', 102)
('Columbia', 'United States', 'Missouri', 'Central', 103)
('Columbia', 'United States', 'South Carolina', 'South', 104)
('Columbia', 'United States', 'Tennessee', 'South', 105)
('Columbus', 'United States', 'Georgia', 'South', 106)
('Columbus', 'United States', 'Indiana', 'Central', 107)
('Columbus', 'United States', 'Ohio', 'East', 108)
('Commerce City', 'United States', 'Colorado', 'West', 109)
('Concord', 'United States', 'California', 'West', 110)
('Concord', 'United States', 'New Hampshire', 'East', 111)
('Concord', 'United States', 'North Carolina', 'South', 112)
('Conway', 'United States', 'Arkansas', 'South', 113)
('Coon Rapids', 'United States', 'Minnesota', 'Central', 114)
('Coppell', 'United States', 'Texas', 'Central', 115)
('Coral Gables', 'United States', 'Florida', 'South', 116)
('Coral Springs', 'United States', 'Florida', 'South', 117)
('Corpus Christi', 'United States', 'Texas', 'Central', 118)
('Costa Mesa', 'United States', 'California', 'West', 119)
('Cottage Grove', 'United States', 'Minnesota', 'Central', 120)
('Covington', 'United States', 'Washington', 'West', 121)
('Cranston', 'United States', 'Rhode Island', 'East', 122)
('Cuyahoga Falls', 'United States', 'Ohio', 'East', 123)
('Dallas', 'United States', 'Texas', 'Central', 124)
('Danville', 'United States', 'California', 'West', 125)
('Danville', 'United States', 'Illinois', 'Central', 126)
('Davis', 'United States', 'California', 'West', 127)
('Daytona Beach', 'United States', 'Florida', 'South', 128)
('Dearborn', 'United States', 'Michigan', 'Central', 129)
('Dearborn Heights', 'United States', 'Michigan', 'Central', 130)
('Decatur', 'United States', 'Alabama', 'South', 131)
('Decatur', 'United States', 'Illinois', 'Central', 132)
('Delray Beach', 'United States', 'Florida', 'South', 133)
('Deltona', 'United States', 'Florida', 'South', 134)
('Denver', 'United States', 'Colorado', 'West', 135)
('Des Moines', 'United States', 'Iowa', 'Central', 136)
('Des Moines', 'United States', 'Washington', 'West', 137)
('Des Plaines', 'United States', 'Illinois', 'Central', 138)
('Detroit', 'United States', 'Michigan', 'Central', 139)
('Dover', 'United States', 'Delaware', 'East', 140)
('Dover', 'United States', 'New Hampshire', 'East', 141)
('Draper', 'United States', 'Utah', 'West', 142)
('Dublin', 'United States', 'California', 'West', 143)
('Dublin', 'United States', 'Ohio', 'East', 144)
('Dubuque', 'United States', 'Iowa', 'Central', 145)
('Durham', 'United States', 'North Carolina', 'South', 146)
('Eagan', 'United States', 'Minnesota', 'Central', 147)
('East Orange', 'United States', 'New Jersey', 'East', 148)
('East Point', 'United States', 'Georgia', 'South', 149)
('Eau Claire', 'United States', 'Wisconsin', 'Central', 150)
('Edinburg', 'United States', 'Texas', 'Central', 151)
('Edmond', 'United States', 'Oklahoma', 'Central', 152)
('Edmonds', 'United States', 'Washington', 'West', 153)
('El Cajon', 'United States', 'California', 'West', 154)
('El Paso', 'United States', 'Texas', 'Central', 155)
('Elkhart', 'United States', 'Indiana', 'Central', 156)
('Elmhurst', 'United States', 'Illinois', 'Central', 157)
('Elyria', 'United States', 'Ohio', 'East', 158)
('Encinitas', 'United States', 'California', 'West', 159)
('Englewood', 'United States', 'Colorado', 'West', 160)
('Escondido', 'United States', 'California', 'West', 161)
('Eugene', 'United States', 'Oregon', 'West', 162)
('Evanston', 'United States', 'Illinois', 'Central', 163)
('Everett', 'United States', 'Massachusetts', 'East', 164)
('Everett', 'United States', 'Washington', 'West', 165)
('Fairfield', 'United States', 'California', 'West', 166)
('Fairfield', 'United States', 'Connecticut', 'East', 167)
('Fairfield', 'United States', 'Ohio', 'East', 168)
('Fargo', 'United States', 'North Dakota', 'Central', 169)
('Farmington', 'United States', 'New Mexico', 'West', 170)
('Fayetteville', 'United States', 'Arkansas', 'South', 171)
('Fayetteville', 'United States', 'North Carolina', 'South', 172)
('Florence', 'United States', 'Alabama', 'South', 173)
('Florence', 'United States', 'Kentucky', 'South', 174)
('Florence', 'United States', 'South Carolina', 'South', 175)
('Fort Collins', 'United States', 'Colorado', 'West', 176)
('Fort Lauderdale', 'United States', 'Florida', 'South', 177)
('Fort Worth', 'United States', 'Texas', 'Central', 178)
('Frankfort', 'United States', 'Illinois', 'Central', 179)
('Franklin', 'United States', 'Massachusetts', 'East', 180)
('Franklin', 'United States', 'Tennessee', 'South', 181)
('Franklin', 'United States', 'Wisconsin', 'Central', 182)
('Freeport', 'United States', 'Illinois', 'Central', 183)
('Freeport', 'United States', 'New York', 'East', 184)
('Fremont', 'United States', 'Nebraska', 'Central', 185)
('Fresno', 'United States', 'California', 'West', 186)
('Frisco', 'United States', 'Texas', 'Central', 187)
('Gaithersburg', 'United States', 'Maryland', 'East', 188)
('Garden City', 'United States', 'Kansas', 'Central', 189)
('Garland', 'United States', 'Texas', 'Central', 190)
('Gastonia', 'United States', 'North Carolina', 'South', 191)
('Georgetown', 'United States', 'Kentucky', 'South', 192)
('Gilbert', 'United States', 'Arizona', 'West', 193)
('Gladstone', 'United States', 'Missouri', 'Central', 194)
('Glendale', 'United States', 'Arizona', 'West', 195)
('Glenview', 'United States', 'Illinois', 'Central', 196)
('Goldsboro', 'United States', 'North Carolina', 'South', 197)
('Grand Island', 'United States', 'Nebraska', 'Central', 198)
('Grand Prairie', 'United States', 'Texas', 'Central', 199)
('Grand Rapids', 'United States', 'Michigan', 'Central', 200)
('Grapevine', 'United States', 'Texas', 'Central', 201)
('Great Falls', 'United States', 'Montana', 'West', 202)
('Greeley', 'United States', 'Colorado', 'West', 203)
('Green Bay', 'United States', 'Wisconsin', 'Central', 204)
('Greensboro', 'United States', 'North Carolina', 'South', 205)
('Greenville', 'United States', 'North Carolina', 'South', 206)
('Greenwood', 'United States', 'Indiana', 'Central', 207)
('Gresham', 'United States', 'Oregon', 'West', 208)
('Grove City', 'United States', 'Ohio', 'East', 209)
('Gulfport', 'United States', 'Mississippi', 'South', 210)
('Hackensack', 'United States', 'New Jersey', 'East', 211)
('Hagerstown', 'United States', 'Maryland', 'East', 212)
('Haltom City', 'United States', 'Texas', 'Central', 213)
('Hamilton', 'United States', 'Ohio', 'East', 214)
('Hampton', 'United States', 'Virginia', 'South', 215)
('Harlingen', 'United States', 'Texas', 'Central', 216)
('Harrisonburg', 'United States', 'Virginia', 'South', 217)
('Hattiesburg', 'United States', 'Mississippi', 'South', 218)
('Helena', 'United States', 'Montana', 'West', 219)
('Hempstead', 'United States', 'New York', 'East', 220)
('Henderson', 'United States', 'Kentucky', 'South', 221)
('Henderson', 'United States', 'Nevada', 'West', 222)
('Hendersonville', 'United States', 'Tennessee', 'South', 223)
('Hesperia', 'United States', 'California', 'West', 224)
('Hialeah', 'United States', 'Florida', 'South', 225)
('Hickory', 'United States', 'North Carolina', 'South', 226)
('Highland Park', 'United States', 'Illinois', 'Central', 227)
('Hillsboro', 'United States', 'Oregon', 'West', 228)
('Holland', 'United States', 'Michigan', 'Central', 229)
('Hollywood', 'United States', 'Florida', 'South', 230)
('Holyoke', 'United States', 'Massachusetts', 'East', 231)
('Homestead', 'United States', 'Florida', 'South', 232)
('Hoover', 'United States', 'Alabama', 'South', 233)
('Hot Springs', 'United States', 'Arkansas', 'South', 234)
('Houston', 'United States', 'Texas', 'Central', 235)
('Huntington Beach', 'United States', 'California', 'West', 236)
('Huntsville', 'United States', 'Alabama', 'South', 237)
('Huntsville', 'United States', 'Texas', 'Central', 238)
('Independence', 'United States', 'Missouri', 'Central', 239)
('Indianapolis', 'United States', 'Indiana', 'Central', 240)
('Inglewood', 'United States', 'California', 'West', 241)
('Iowa City', 'United States', 'Iowa', 'Central', 242)
('Irving', 'United States', 'Texas', 'Central', 243)
('Jackson', 'United States', 'Michigan', 'Central', 244)
('Jackson', 'United States', 'Mississippi', 'South', 245)
('Jackson', 'United States', 'Tennessee', 'South', 246)
('Jacksonville', 'United States', 'Florida', 'South', 247)
('Jacksonville', 'United States', 'North Carolina', 'South', 248)
('Jamestown', 'United States', 'New York', 'East', 249)
('Jefferson City', 'United States', 'Missouri', 'Central', 250)
('Johnson City', 'United States', 'Tennessee', 'South', 251)
('Jonesboro', 'United States', 'Arkansas', 'South', 252)
('Jupiter', 'United States', 'Florida', 'South', 253)
('Keller', 'United States', 'Texas', 'Central', 254)
('Kenner', 'United States', 'Louisiana', 'South', 255)
('Kenosha', 'United States', 'Wisconsin', 'Central', 256)
('Kent', 'United States', 'Ohio', 'East', 257)
('Kent', 'United States', 'Washington', 'West', 258)
('Kirkwood', 'United States', 'Missouri', 'Central', 259)
('Kissimmee', 'United States', 'Florida', 'South', 260)
('Knoxville', 'United States', 'Tennessee', 'South', 261)
('La Crosse', 'United States', 'Wisconsin', 'Central', 262)
('La Mesa', 'United States', 'California', 'West', 263)
('La Porte', 'United States', 'Indiana', 'Central', 264)
('La Porte', 'United States', 'Texas', 'Central', 265)
('La Quinta', 'United States', 'California', 'West', 266)
('Lafayette', 'United States', 'Indiana', 'Central', 267)
('Lafayette', 'United States', 'Louisiana', 'South', 268)
('Laguna Niguel', 'United States', 'California', 'West', 269)
('Lake Charles', 'United States', 'Louisiana', 'South', 270)
('Lake Elsinore', 'United States', 'California', 'West', 271)
('Lake Forest', 'United States', 'California', 'West', 272)
('Lakeland', 'United States', 'Florida', 'South', 273)
('Lakeville', 'United States', 'Minnesota', 'Central', 274)
('Lakewood', 'United States', 'California', 'West', 275)
('Lakewood', 'United States', 'New Jersey', 'East', 276)
('Lakewood', 'United States', 'Ohio', 'East', 277)
('Lancaster', 'United States', 'California', 'West', 278)
('Lancaster', 'United States', 'Ohio', 'East', 279)
('Lancaster', 'United States', 'Pennsylvania', 'East', 280)
('Lansing', 'United States', 'Michigan', 'Central', 281)
('Laredo', 'United States', 'Texas', 'Central', 282)
('Las Cruces', 'United States', 'New Mexico', 'West', 283)
('Las Vegas', 'United States', 'Nevada', 'West', 284)
('Laurel', 'United States', 'Maryland', 'East', 285)
('Lawrence', 'United States', 'Indiana', 'Central', 286)
('Lawrence', 'United States', 'Massachusetts', 'East', 287)
('Lawton', 'United States', 'Oklahoma', 'Central', 288)
('Layton', 'United States', 'Utah', 'West', 289)
('League City', 'United States', 'Texas', 'Central', 290)
('Lebanon', 'United States', 'Tennessee', 'South', 291)
('Lehi', 'United States', 'Utah', 'West', 292)
('Leominster', 'United States', 'Massachusetts', 'East', 293)
('Lewiston', 'United States', 'Idaho', 'West', 294)
('Lewiston', 'United States', 'Maine', 'East', 295)
('Lincoln Park', 'United States', 'Michigan', 'Central', 296)
('Linden', 'United States', 'New Jersey', 'East', 297)
('Lindenhurst', 'United States', 'New York', 'East', 298)
('Little Rock', 'United States', 'Arkansas', 'South', 299)
('Littleton', 'United States', 'Colorado', 'West', 300)
('Lodi', 'United States', 'California', 'West', 301)
('Logan', 'United States', 'Utah', 'West', 302)
('Long Beach', 'United States', 'California', 'West', 303)
('Long Beach', 'United States', 'New York', 'East', 304)
('Longmont', 'United States', 'Colorado', 'West', 305)
('Longview', 'United States', 'Washington', 'West', 306)
('Lorain', 'United States', 'Ohio', 'East', 307)
('Los Angeles', 'United States', 'California', 'West', 308)
('Louisville', 'United States', 'Colorado', 'West', 309)
('Louisville', 'United States', 'Kentucky', 'South', 310)
('Loveland', 'United States', 'Colorado', 'West', 311)
('Lowell', 'United States', 'Massachusetts', 'East', 312)
('Lubbock', 'United States', 'Texas', 'Central', 313)
('Macon', 'United States', 'Georgia', 'South', 314)
('Madison', 'United States', 'Wisconsin', 'Central', 315)
('Malden', 'United States', 'Massachusetts', 'East', 316)
('Manchester', 'United States', 'Connecticut', 'East', 317)
('Manhattan', 'United States', 'Kansas', 'Central', 318)
('Mansfield', 'United States', 'Texas', 'Central', 319)
('Manteca', 'United States', 'California', 'West', 320)
('Maple Grove', 'United States', 'Minnesota', 'Central', 321)
('Margate', 'United States', 'Florida', 'South', 322)
('Marietta', 'United States', 'Georgia', 'South', 323)
('Marion', 'United States', 'Iowa', 'Central', 324)
('Marion', 'United States', 'Ohio', 'East', 325)
('Marlborough', 'United States', 'Massachusetts', 'East', 326)
('Marysville', 'United States', 'Washington', 'West', 327)
('Mason', 'United States', 'Ohio', 'East', 328)
('Mcallen', 'United States', 'Texas', 'Central', 329)
('Medford', 'United States', 'Oregon', 'West', 330)
('Medina', 'United States', 'Ohio', 'East', 331)
('Melbourne', 'United States', 'Florida', 'South', 332)
('Memphis', 'United States', 'Tennessee', 'South', 333)
('Mentor', 'United States', 'Ohio', 'East', 334)
('Meriden', 'United States', 'Connecticut', 'East', 335)
('Meridian', 'United States', 'Idaho', 'West', 336)
('Mesa', 'United States', 'Arizona', 'West', 337)
('Mesquite', 'United States', 'Texas', 'Central', 338)
('Miami', 'United States', 'Florida', 'South', 339)
('Middletown', 'United States', 'Connecticut', 'East', 340)
('Midland', 'United States', 'Michigan', 'Central', 341)
('Milford', 'United States', 'Connecticut', 'East', 342)
('Milwaukee', 'United States', 'Wisconsin', 'Central', 343)
('Minneapolis', 'United States', 'Minnesota', 'Central', 344)
('Miramar', 'United States', 'Florida', 'South', 345)
('Mishawaka', 'United States', 'Indiana', 'Central', 346)
('Mission Viejo', 'United States', 'California', 'West', 347)
('Missouri City', 'United States', 'Texas', 'Central', 348)
('Mobile', 'United States', 'Alabama', 'South', 349)
('Modesto', 'United States', 'California', 'West', 350)
('Monroe', 'United States', 'Louisiana', 'South', 351)
('Monroe', 'United States', 'North Carolina', 'South', 352)

### Adress

In [5]:
name_table = "adress"

# 1. Open the workbook and define the worksheet
sheet = book.sheet_by_name(f"{name_table}")

# 2. Get the cursor, which is used to traverse the database, line by line
cursor = database.cursor()

In [6]:
# 3, Create the INSERT INTO sql query
query = f"""INSERT INTO {name_table} (Postal_Code, city_id) VALUES (%s, %s)"""

# 4. Create a For loop to iterate through each row in the XLS file, starting at row 2 to skip the headers
for r in range(1, sheet.nrows):
    if sheet.cell(r,0).value != '':
        col_name_0 = int(sheet.cell(r,0).value)
        col_name_1  = int(sheet.cell(r,1).value)
        
        # Assign values from each row
        values = (col_name_0, col_name_1)
        print(values)

        # Execute sql Query
        cursor.execute(query, values)
    else:
        pass

# Close the cursor
cursor.close()
# Commit the transaction
database.commit()
# Close the database connection
database.close()

# 5. Status
print('ETL - copleted')

(1040, 231)
(1453, 293)
(1752, 326)
(1810, 11)
(1841, 287)
(1852, 312)
(1915, 44)
(2038, 182)
(2138, 72)
(2148, 316)
(2149, 165)
(2151, 458)
(2169, 445)
(2740, 371)
(2886, 568)
(2895, 593)
(2908, 441)
(2920, 122)
(3060, 368)
(3301, 112)
(3820, 141)
(4240, 295)
(4401, 34)
(6010, 59)
(6040, 317)
(6360, 387)
(6450, 335)
(6457, 340)
(6460, 342)
(6484, 513)
(6708, 570)
(6824, 168)
(7002, 36)
(7011, 96)
(7017, 148)
(7036, 297)
(7050, 399)
(7055, 416)
(7060, 429)
(7090, 579)
(7109, 40)
(7501, 417)
(7601, 211)
(7960, 358)
(8302, 57)
(8360, 563)
(8401, 25)
(8701, 277)
(8861, 423)
(8901, 372)
(10009, 375)
(10011, 375)
(10024, 375)
(10035, 375)
(10550, 361)
(10701, 594)
(10801, 374)
(11520, 184)
(11550, 220)
(11561, 304)
(11572, 392)
(11757, 298)
(12180, 552)
(13021, 27)
(13440, 471)
(13501, 559)
(13601, 572)
(14215, 64)
(14304, 379)
(14609, 466)
(14701, 249)
(16602, 8)
(17403, 595)
(17602, 280)
(18018, 43)
(18103, 7)
(19013, 87)
(19120, 425)
(19134, 425)
(19140, 425)
(19143, 425)
(19601, 449)
(19711, 377)
(19805, 587)
(19901, 141)
(20016, 569)
(20707, 285)
(20735, 97)
(20852, 469)
(20877, 188)
(21044, 105)
(21215, 33)
(21740, 212)
(22153, 527)
(22204, 19)
(22304, 5)
(22801, 217)
(22901, 84)
(22980, 575)
(23223, 462)
(23320, 86)
(23434, 530)
(23464, 564)
(23602, 378)
(23666, 215)
(24153, 489)
(26003, 583)
(27217, 69)
(27360, 543)
(27405, 205)
(27511, 77)
(27514, 82)
(27534, 197)
(27604, 446)
(27707, 146)
(27834, 206)
(27893, 588)
(28027, 112)
(28052, 191)
(28110, 352)
(28205, 83)
(28314, 172)
(28403, 587)
(28540, 248)
(28601, 226)
(28806, 22)
(29203, 105)
(29406, 384)
(29464, 360)
(29483, 531)
(29501, 175)
(29730, 467)
(30062, 323)
(30076, 476)
(30080, 518)
(30188, 592)
(30318, 24)
(30328, 503)
(30344, 149)
(30605, 23)
(31088, 567)
(31204, 314)
(31907, 108)
(32114, 128)
(32127, 437)
(32137, 409)
(32174, 403)
(32216, 248)
(32303, 534)
(32503, 420)
(32712, 14)
(32725, 134)
(32771, 504)
(32839, 402)
(32935, 332)
(33012, 225)
(33021, 230)
(33023, 345)
(33024, 419)
(33030, 232)
(33063, 322)
(33065, 117)
(33068, 435)
(33134, 116)
(33142, 339)
(33161, 386)
(33178, 339)
(33180, 339)
(33311, 177)
(33317, 431)
(33319, 535)
(33407, 578)
(33433, 48)
(33437, 54)
(33445, 133)
(33458, 253)
(33614, 536)
(33710, 487)
(33801, 273)
(34741, 260)
(34952, 438)
(35244, 233)
(35401, 555)
(35601, 132)
(35630, 175)
(35810, 238)
(36116, 354)
(36608, 349)
(36830, 27)
(37042, 94)
(37064, 182)
(37075, 223)
(37087, 291)
(37130, 362)
(37167, 518)
(37211, 369)
(37421, 85)
(37604, 251)
(37620, 59)
(37918, 261)
(38109, 333)
(38134, 35)
(38301, 246)
(38401, 105)
(38671, 520)
(39212, 246)
(39401, 218)
(39503, 210)
(40214, 310)
(40324, 192)
(40475, 462)
(41042, 175)
(42071, 364)
(42104, 53)
(42301, 406)
(42420, 222)
(43017, 144)
(43055, 377)
(43123, 209)
(43130, 280)
(43229, 108)
(43302, 325)
(43402, 53)
(43615, 548)
(44035, 158)
(44052, 307)
(44060, 334)
(44105, 95)
(44107, 277)
(44134, 412)
(44221, 123)
(44240, 258)
(44256, 331)
(44312, 3)
(45011, 214)
(45014, 168)
(45040, 328)
(45231, 92)
(45373, 552)
(45503, 527)
(46060, 380)
(46142, 207)
(46203, 240)
(46226, 287)
(46350, 265)
(46368, 439)
(46514, 156)
(46544, 346)
(46614, 519)
(47150, 370)
(47201, 108)
(47362, 373)
(47374, 462)
(47401, 47)
(47905, 268)
(48066, 475)
(48073, 478)
(48104, 12)
(48126, 129)
(48127, 130)
(48146, 296)
(48180, 537)
(48183, 550)
(48185, 580)
(48187, 73)
(48205, 139)
(48227, 139)
(48234, 139)
(48237, 389)
(48310, 528)
(48601, 480)
(48640, 341)
(48858, 360)
(48911, 281)
(49201, 246)
(49423, 229)
(49505, 200)
(50315, 137)
(50322, 558)
(50701, 571)
(52001, 145)
(52240, 242)
(52302, 325)
(52402, 79)
(52601, 69)
(53081, 512)
(53132, 182)
(53142, 256)
(53186, 573)
(53209, 343)
(53214, 576)
(53711, 315)
(54302, 204)
(54401, 574)
(54601, 262)
(54703, 150)
(54880, 533)
(54915, 17)
(55016, 120)
(55044, 274)
(55106, 485)
(55113, 475)
(55122, 147)
(55124, 16)
(55125, 589)
(55369, 321)
(55407, 344)
(55433, 114)
(55901, 466)
(56301, 483)
(56560, 355)
(57103, 515)
(57401, 1)
(57701, 448)
(58103, 169)
(59102, 45)
(59405, 202)
(59601, 219)
(59715, 55)
(60004, 20)
(60016, 138)
(60025, 196)
(60035, 227)
(60067, 408)
(60068, 410)
(60076, 516)
(60089, 65)
(60090, 583)
(60098, 592)
(60126, 157)
(60174, 482)
(60188, 75)
(60201, 163)
(60302, 389)
(60423, 179)
(60440, 50)
(60441, 472)
(60462, 401)
(60477, 547)
(60505, 29)
(60540, 367)
(60543, 404)
(60610, 89)
(60623, 89)
(60653, 89)
(61032, 184)
(61107, 468)
(61604, 422)
(61701, 47)
(61761, 382)
(61821, 80)
(61832, 126)
(62301, 445)
(62521, 132)
(63116, 484)
(63122, 259)
(63301, 482)
(63376, 486)
(64055, 239)
(64118, 194)
(65109, 250)
(65203, 105)
(65807, 527)
(66062, 395)
(66212, 405)
(66502, 318)
(67212, 585)
(67846, 189)
(68025, 185)
(68104, 397)
(68701, 381)
(68801, 198)
(70065, 255)
(70506, 268)
(70601, 270)
(71111, 51)
(71203, 352)
(71603, 428)
(71854, 540)
(71901, 234)
(72032, 113)
(72209, 299)
(72401, 252)
(72701, 172)
(72756, 470)
(72762, 523)
(73034, 152)
(73071, 383)
(73120, 394)
(73505, 288)
(74012, 60)
(74133, 554)
(74403, 366)
(75002, 6)
(75007, 76)
(75019, 115)
(75023, 430)
(75034, 187)
(75043, 190)
(75051, 199)
(75056, 542)
(75061, 243)
(75080, 459)
(75081, 124)
(75104, 78)
(75150, 338)
(75217, 124)
(75220, 124)
(75701, 557)
(76017, 19)
(76021, 39)
(76051, 201)
(76063, 319)
(76106, 178)
(76117, 213)
(76248, 254)
(76706, 566)
(76903, 492)
(77036, 235)
(77041, 235)
(77070, 235)
(77095, 235)
(77340, 238)
(77489, 348)
(77506, 414)
(77520, 37)
(77571, 265)
(77573, 290)
(77581, 418)
(77590, 541)
(77642, 436)
(77705, 38)
(77803, 63)
(77840, 100)
(78041, 282)
(78207, 493)
(78415, 118)
(78501, 329)
(78521, 62)
(78539, 151)
(78550, 216)
(78577, 424)
(78664, 477)
(78666, 501)
(78745, 30)
(79109, 9)
(79424, 313)
(79605, 2)
(79762, 393)
(79907, 155)
(80004, 21)
(80013, 29)
(80020, 61)
(80022, 109)
(80027, 310)
(80112, 160)
(80122, 300)
(80134, 411)
(80219, 135)
(80229, 544)
(80501, 305)
(80525, 176)
(80538, 311)
(80634, 203)
(80906, 101)
(81001, 443)
(82001, 88)
(83201, 433)
(83301, 556)
(83501, 295)
(83605, 70)
(83642, 336)
(83704, 49)
(84020, 142)
(84041, 289)
(84043, 292)
(84057, 400)
(84062, 432)
(84084, 577)
(84106, 491)
(84107, 364)
(84321, 302)
(84604, 442)
(85023, 426)
(85204, 337)
(85224, 81)
(85234, 193)
(85254, 510)
(85281, 539)
(85301, 195)
(85323, 31)
(85345, 422)
(85364, 597)
(85635, 514)
(85705, 553)
(86442, 66)
(87105, 4)
(87124, 463)
(87401, 170)
(87505, 508)
(88001, 283)
(88101, 98)
(88220, 74)
(89015, 222)
(89031, 385)
(89115, 284)
(89431, 521)
(89502, 456)
(90004, 308)
(90008, 308)
(90032, 308)
(90036, 308)
(90045, 308)
(90049, 308)
(90278, 454)
(90301, 241)
(90503, 549)
(90604, 584)
(90640, 353)
(90660, 427)
(90712, 277)
(90805, 304)
(91104, 414)
(91360, 545)
(91505, 67)
(91730, 447)
(91761, 398)
(91767, 434)
(91776, 498)
(91911, 91)
(91941, 263)
(92020, 154)
(92024, 159)
(92025, 161)
(92037, 496)
(92054, 392)
(92105, 496)
(92236, 99)
(92253, 266)
(92307, 16)
(92345, 224)
(92374, 451)
(92399, 596)
(92404, 494)
(92503, 464)
(92530, 271)
(92553, 356)
(92563, 365)
(92592, 538)
(92627, 119)
(92630, 272)
(92646, 236)
(92672, 495)
(92677, 269)
(92683, 581)
(92691, 347)
(92704, 505)
(92804, 10)
(93010, 71)
(93030, 407)
(93101, 506)
(93277, 565)
(93309, 32)
(93405, 500)
(93454, 509)
(93534, 280)
(93727, 186)
(93905, 490)
(94061, 455)
(94086, 532)
(94109, 497)
(94110, 497)
(94122, 497)
(94403, 502)
(94509, 13)
(94513, 56)
(94521, 112)
(94526, 126)
(94533, 168)
(94568, 144)
(94591, 561)
(94601, 390)
(95037, 357)
(95051, 507)
(95123, 499)
(95207, 529)
(95240, 301)
(95336, 320)
(95351, 350)
(95610, 93)
(95616, 127)
(95661, 475)
(95687, 560)
(95695, 590)
(95823, 479)
(95928, 90)
(96003, 450)
(97030, 208)
(97123, 228)
(97206, 440)
(97224, 546)
(97301, 489)
(97405, 162)
(97477, 527)
(97504, 330)
(97756, 453)
(98006, 41)
(98026, 153)
(98031, 258)
(98042, 121)
(98052, 453)
(98059, 457)
(98103, 511)
(98105, 511)
(98115, 511)
(98198, 137)
(98208, 165)
(98226, 42)
(98270, 327)
(98502, 396)
(98632, 306)
(98661, 562)
(99207, 522)
(99301, 415)
ETL - copleted

### Customer

In [3]:
name_table = "customer"

# 1. Open the workbook and define the worksheet
sheet = book.sheet_by_name(f"{name_table}")

# 2. Get the cursor, which is used to traverse the database, line by line
cursor = database.cursor()

In [4]:
# 3, Create the INSERT INTO sql query
query = f"""INSERT INTO {name_table} (Customer_ID, Customer_Name, segment_id, Postal_Code) VALUES (%s, %s, %s, %s)"""

# 4. Create a For loop to iterate through each row in the XLS file, starting at row 2 to skip the headers
for r in range(1, sheet.nrows):
    if sheet.cell(r,0).value != '':
        col_name_0 = sheet.cell(r,0).value
        col_name_1  = sheet.cell(r,1).value
        col_name_2  = int(sheet.cell(r,2).value)
        col_name_3  = int(sheet.cell(r,3).value)
        
        # Assign values from each row
        values = (col_name_0, col_name_1,col_name_2, col_name_3)
        print(values)

        # Execute sql Query
        cursor.execute(query, values)
    else:
        pass

# Close the cursor
cursor.close()
# Commit the transaction
database.commit()
# Close the database connection
database.close()

# 5. Status
print('ETL - copleted')

('AA-10315', 'Alex Avila', 1, 10011)
('AA-10315', 'Alex Avila', 1, 78664)

IntegrityError: (1062, "Duplicate entry 'AA-10315' for key 'customer.PRIMARY'")